#!/usr/bin/env zsh

if [ -d "$HOME/.config/profile.d" ]; then
  for i in $(printf '%s\n' "$HOME/.config/profile.d/"*.sh | LC_ALL=C sort -V); do
    if [ -r "$i" ]; then
      source "$i"
    fi
  done
  unset i
fi