#!/usr/bin/env bash

# bash <(curl https://raw.githubusercontent.com/KaidenP/dotfiles/master/linux/shared/.bin/autoinstall)

copy_files() {
  for dir in "./shared" "./linux/shared" "./linux/$DISTRIB_ID/all" "./linux/$DISTRIB_ID/$DISTRIB_RELEASE"; do
    echo "Copying $dir to $HOME..."
    if [ -d "$dir" ]; then
      tar -cC "$dir" . | tar -xC "$HOME/"
    else
      echo "$dir does not exist. Skipping..."
    fi
  done
}

REPO="https://github.com/KaidenP/dotfiles.git"
REPO_DIR="$HOME/.dotfiles"
if [ -d "$REPO_DIR" ]; then
  if command -v git &> /dev/null; then
    cd "$REPO_DIR"
    git pull origin master
  fi
else
  if ! command -v git &> /dev/null; then
    echo "Git is required for this script"
    exit 255
  fi
  git clone "$REPO" "$REPO_DIR"
fi
cd "$REPO_DIR"

SUDO=""
if [[ $EUID -ne 0 ]]; then
	echo "Using sudo for admin commands."
	echo "==================="
	SUDO="sudo"
fi

DISTRIB_ID="unknown"
DISTRIB_RELEASE=""
DISTRIB_CODENAME=""
DISTRIB_DESCRIPTION=""

LSB_RELEASE="/etc/lsb-release"
if test -f "$LSB_RELEASE"; then
    source "$LSB_RELEASE"
else
  echo "No $LSB_RELEASE found."
fi

if [[ "$DISTRIB_ID" == "unknown" ]]; then
  echo "unknown distribution. Exiting..."
  exit 255
else
  copy_files
  bash "$HOME/.bin/install_dotfiles"
fi

# NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
$SUDO chown $USER:$USER ~ -R
copy_files
chmod 700 -R ~/.ssh ~/.bin &> /dev/null
chmod 600 -f ~/.ssh/* ~/.ssh/*.*  &> /dev/null

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install node
npm install -g yarn


cd "$HOME"
exec zsh
