#!/bin/bash
DOTFILES=$(dirname $(dirname $(realpath $0)))
source "$DOTFILES/.bin/shared/lib.bash"

SUDO=""
APT="apt-get -y"

PKGS_WANT="wget curl build-essential aria2 git zsh tmux"
PKGS="$PKGS_WANT"

log "Setting up for ${USER}. "
if [[ $EUID -ne 0 ]]; then
	log_warn "Using sudo for admin commands."
	echo "==================="
	SUDO="sudo"
fi

$SUDO $APT update
$SUDO $APT upgrade
$SUDO $APT dist-upgrade
$SUDO $APT install $PKGS

#ZSH
$SUDO chsh -s "$(which zsh)" "$(whoami)"
zsh <(curl -fsSL https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh)
##plugins
sh -c "$(curl -fsSL https://raw.githubusercontent.com/psprint/zsh-navigation-tools/master/doc/install.sh)"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors
if [ -d "$HOME/.powerlevel10k" ]; then
	cd "$HOME/.powerlevel10k"
	git pull origin master
else
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME/.powerlevel10k"
fi

echo "Done!!"
cd ~
# exec zsh


# cp files
# if [ "$DOTFILES" != "$HOME" ]; then
# 	log "Coppying $DOTFILES to $HOME..."
# 	tar -vcC "$DOTFILES" . | tar -xC ~/
# fi
#
# $SUDO chown $USER:$USER ~ -R
# chmod 700 -R ~/.ssh ~/.bin
# chmod 600 -f ~/.ssh/* ~/.ssh/*.*
